sonar.projectKey=laravel-jjkt-penjaminan-service-test
sonar.projectName=jjkt-penjaminan-test
sonar.sources=app/Jobs,app/Support,app/Http/Controllers/Controller.php,app/Http/Controllers/MultigunaServices/MultigunaBulkDummyController.php,app/Helpers/ApiResponse.php,app/Providers,routes
sonar.coverage.exclusions=app/Http/Controllers/Controller.php,app/Providers/**,app/Support/**,routes/**
sonar.sourceEncoding=UTF-8
