[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true

[program:rabbitmq-consumer]
command=php /var/www/artisan rabbitmq:consume q.creatio.to-mitra
directory=/var/www
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/rabbitmq-consumer.log
stopwaitsecs=3600
